#!/usr/bin/php
<?php
/**
 * fix-ocr
 *
 * Script that converts reserved characters in hocr output
 * generated by tesseract with right entities.
 */

// Includes
require('./lib/simplehtmldom/simple_html_dom.php');

$html = file_get_html($argv[1]);

// Write a function with parameter "$element"
function my_callback($element) {
	if (isset($element->attr['class']) && $element->attr['class']=='xocr_word')
		$element->innertext = htmlspecialchars($element->innertext, ENT_COMPAT, 'UTF-8');
}

// Register the callback function with it's function name
$html->set_callback('my_callback');

// Save the file
$html->save($argv[2]);

?>

