#!/usr/bin/env python3
#
# Shrink ACO PDF files generated by QNL.
#
# Requires the following tools:
# ImageMagick, poppler, pdf2djvu, ocrodjvu, and hocr-tools
#
# rasan@nyu.edu

import argparse
import functools
import glob
import logging
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pprint import pformat

import PIL.Image

sys.path.append("/usr/local/dlib/task-queue")
from tqcommon import get_rstar_dir

RSTAR_DIR = get_rstar_dir()

SUPPORTED_DPI = (72, 96, 200)
DEFAULT_DPI = 72

logger = logging.getLogger(__name__)

print = functools.partial(print, flush=True)


def log_output(name, output):
    if output:
        if isinstance(output, bytes):
            output = output.decode(errors="replace")
        logger.error("%s:\n%s", name, output)


def do_cmd(cmdlist, **kwargs):
    cmd = list(map(str, cmdlist))
    cmd_str = " ".join(cmd)
    logger.debug("Running command: %s", cmd_str)
    try:
        process = subprocess.run(cmd, check=True, **kwargs)
    except subprocess.CalledProcessError as e:
        logger.error(
            "Command '%s' failed with exit code %d", cmd_str, e.returncode
        )
        log_output("stdout", e.stdout)
        log_output("stderr", e.stderr)
        sys.exit(1)
    return process


def round_down_to_even(num):
    return math.floor(float(num) / 2.0) * 2


def get_img_data(col_idx, output_line):
    """Parse a pdfimages output line into a dictionary of metadata values.

    Args:
        col_idx: Dictionary mapping metadata names to their column indexes.
        output_line: A line of output from pdfimages.

    Returns:
        Dictionary mapping metadata names to their values from output_line.
    """
    val_list = output_line.split()
    logger.debug("val_list: %s", pformat(val_list))

    img_data = {name: val_list[col_idx[name]] for name in col_idx}
    logger.debug("img_data: %s", pformat(img_data))

    return img_data


def get_img_info(pdf_file):
    """Get image information from a PDF file using pdfimages tool.

    Args:
        pdf_file: Path to the PDF file.

    Returns:
        A dictionary containing the image file extension, DPI, and whether
        the PDF contains an image mask, or None if the PDF contains no images.
    """
    ret = do_cmd(
        ["pdfimages", "-l", 1, "-list", pdf_file],
        stdout=subprocess.PIPE,
        universal_newlines=True,
    )

    output = ret.stdout.splitlines()
    logger.debug("pdfimages output: %s", output)

    if len(output) < 3:
        logger.warning(" %s has no images".pdf_file)
        return None

    col_idx = {col: i for i, col in enumerate(output[0].split())}
    logger.debug("column index: %s", pformat(col_idx))

    img_data = get_img_data(col_idx, output[2])

    codec = img_data["enc"]
    dpi = round_down_to_even(img_data["x-ppi"])

    mask = False
    for line in output[2:]:
        logger.debug(line)
        img_data = get_img_data(col_idx, line)
        if img_data["type"] == "mask":
            mask = True
            break

    ext = {"jpeg": "jpg", "jpx": "jp2"}

    return {"ext": ext.get(codec), "dpi": dpi, "mask": mask}


def mv(src, dst):
    logger.debug("Moving %s to %s", src, dst)
    shutil.move(src, dst)


def check_dependencies():
    # Check for required tools
    tools = [
        "convert",
        "djvu2hocr",
        "exiftool",
        "hocr-pdf",
        "pdf2djvu",
        "pdfimages",
        "qpdf",
    ]

    missing = 0
    for prog in tools:
        path = shutil.which(prog)
        if path is None:
            print(f"{prog} not in PATH", file=sys.stderr)
            missing += 1
    if missing > 0:
        sys.exit(1)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Shrink ACO PDFs generated by QNL."
    )
    parser.add_argument(
        "input_file", metavar="INPUT_FILE", help="Input PDF file"
    )
    parser.add_argument(
        "output_file", metavar="OUTPUT_FILE", help="Output PDF file"
    )
    parser.add_argument(
        "-d", "--debug", help="Enable debugging messages", action="store_true"
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=DEFAULT_DPI,
        choices=SUPPORTED_DPI,
        help="Resolution for PDF pages (default: %(default)s)",
    )
    parser.add_argument(
        "-m",
        "--max-pages",
        type=int,
        default=-1,
        help="Maximum number of pages to process",
    )
    parser.add_argument(
        "-t",
        "--tmpdir",
        default=os.path.join(RSTAR_DIR, "tmp"),
        help="Temp directory (default: %(default)s)",
    )
    parser.add_argument(
        "-f",
        "--force",
        help="Force overwrite of output file",
        action="store_true",
    )
    parser.add_argument(
        "--use-existing-hocr",
        action="store_true",
        help="Use existing hOCR files from input directory",
    )
    return parser.parse_args()


def validate_input(args):
    logger.debug("Input file: %s", args.input_file)
    logger.debug("Output file: %s", args.output_file)

    if args.input_file == args.output_file:
        sys.exit("Input file can't be the same as output file.")

    if not args.force and os.path.exists(args.output_file):
        sys.exit("Output file already exists.")


def setup_logging(debug):
    level = logging.DEBUG if debug else logging.INFO

    logging.basicConfig(
        format="%(asctime)s - shrink-aco-pdf - %(levelname)s - %(message)s",
        datefmt="%m/%d/%Y %I:%M:%S %p",
        level=level,
    )


def fatal(msg, *args, **kwargs):
    logger.error(msg, *args, **kwargs)
    sys.exit(1)


def do_shrink(
    input_file,
    output_file,
    workdir,
    dpi,
    *,
    max_pages=-1,
    use_existing_hocr=False,
):
    if os.listdir(workdir):
        fatal("Directory is not empty: %s", workdir)

    if dpi not in SUPPORTED_DPI:
        fatal("Unsupported DPI: %s (supported values: %s)", dpi, SUPPORTED_DPI)

    logger.info("Processing file %s in work dir %s", input_file, workdir)

    input_dir, input_basename = os.path.split(input_file)
    logger.debug("input dir: %s", input_dir)

    hocr_files = sorted(glob.glob(f"{input_dir}/*_hocr.html"))

    aux_exists = False
    objid = os.path.splitext(input_basename)[0]
    match = re.search(r"^([a-z]+)_aco\d{6}$", objid)
    if match:
        partner_id = match.group(1)
        aux_dir = f"{RSTAR_DIR}/content/{partner_id}/aco/wip/se/{objid}/aux"
        logger.debug("aux_dir: %s", aux_dir)
        aux_exists = os.path.isdir(aux_dir)

    # split pdf into individual pdfs for each page
    do_cmd(["qpdf", "--split-pages", input_file, f"{workdir}/%d.pdf"])

    # Loop over each page until we have an hocr file
    # and reduced jpg for each page
    for i, pdf_file in enumerate(sorted(glob.glob(f"{workdir}/*.pdf"))):

        if max_pages > 0 and i == max_pages:
            break

        imginfo = get_img_info(pdf_file)
        logger.debug("imginfo: %s", imginfo)

        if not imginfo:
            sys.exit(f"Can't find any images in {pdf_file}")

        if imginfo["ext"] is None or imginfo["mask"]:
            img_ext = "png"
            pdfimgs_arg = "-png"
        else:
            img_ext = imginfo["ext"]
            pdfimgs_arg = "-all"

        # set up file paths
        basename = os.path.splitext(pdf_file)[0]
        pdfimgs_dir = os.path.join(workdir, f"pdfimgs_{i + 1:03d}")
        pdfimgs_base = os.path.join(pdfimgs_dir, os.path.basename(basename))
        djvu_file = basename + ".djvu"
        hocr_file = basename + ".hocr"
        new_jpg_file = basename + ".jpg"
        old_img_file = pdfimgs_base + "-000." + img_ext

        logger.debug("Creating directory %s", pdfimgs_dir)
        os.mkdir(pdfimgs_dir)

        # extract jpg image from pdf page
        do_cmd(["pdfimages", pdfimgs_arg, pdf_file, pdfimgs_base])

        if imginfo["mask"]:
            bot_layer = old_img_file
            masked = pdfimgs_base + "-001." + img_ext
            old_mask = pdfimgs_base + "-002." + img_ext
            new_mask = pdfimgs_base + "-mask." + img_ext
            top_layer = pdfimgs_base + "-top." + img_ext
            merged = pdfimgs_base + "-merged." + img_ext
            # mask image is twice as large as other images so we
            # must resize it to match them before applying it
            do_cmd(["convert", old_mask, "-resize", "50%", new_mask])
            # apply mask to second image to form top/text layer
            do_cmd([
                "convert",
                masked,
                new_mask,
                "-alpha",
                "Off",
                "-compose",
                "CopyOpacity",
                "-composite",
                top_layer,
            ])
            # merge top/text layer with bottom layer to create
            # final combined image
            do_cmd(["convert", bot_layer, top_layer, "-composite", merged])
            # move merged image so that it can shrunk by
            # imagemagick in step below
            mv(old_img_file, old_img_file + ".bak")
            mv(merged, old_img_file)

        # shrink image size by reducing quality
        do_cmd([
            "convert",
            "-density",
            imginfo["dpi"],
            "-units",
            "PixelsPerInch",
            old_img_file,
            "-resample",
            dpi,
            "-density",
            dpi,
            "-units",
            "PixelsPerInch",
            new_jpg_file,
        ])

        # Check that shrunken image has correct resolution
        with PIL.Image.open(new_jpg_file) as new_jpg:
            new_jpg_dpi = new_jpg.info["dpi"][0]
        logger.debug("dpi %s: %s", new_jpg_file, new_jpg_dpi)
        if new_jpg_dpi != dpi:
            logger.error(
                "Expected dpi %s for %s, found %s instead",
                dpi,
                new_jpg_file,
                new_jpg_dpi,
            )
            sys.exit(1)

        # # delete images extracted from pdfimages
        # logger.debug("Removing directory %s", pdfimgs_dir)
        # shutil.rmtree(pdfimgs_dir)

        if use_existing_hocr:
            # hocr files seem to shifted by 1
            if i == len(hocr_files) - 1:
                j = 0
            else:
                j = i + 1
            logger.debug("Copying %s to %s", hocr_files[j], hocr_file)
            shutil.copyfile(hocr_files[j], hocr_file)
        else:
            # convert pdf page to djvu file
            do_cmd(["pdf2djvu", "-q", "-o", djvu_file, pdf_file])

            # extract hidden text from djvu file as hocr
            with open(hocr_file, "w") as f:
                ret = do_cmd(
                    ["djvu2hocr", djvu_file], stdout=f, stderr=subprocess.PIPE
                )
                logger.debug(ret.stderr.decode().strip())

        # generating hocr is time consuming so we copy file
        # to aux directory for later use
        if aux_exists:
            dest_file = aux_dir + "/" + os.path.basename(hocr_file)
            if not os.path.isfile(dest_file):
                shutil.copyfile(hocr_file, dest_file)

    # reassemble pdf by combining reduced images
    # and extracted hocr files
    tmp_pdf_file = os.path.join(workdir, "tmp.pdf")
    hocr_pdf = [
        "hocr-pdf",
        "--savefile",
        tmp_pdf_file,
    ]
    if use_existing_hocr:
        hocr_pdf.append("--reverse")
    hocr_pdf.append(workdir)
    do_cmd(hocr_pdf)
    do_cmd(["exiftool", "-q", "-m", "-all:all=", tmp_pdf_file])
    do_cmd(["qpdf", "--linearize", tmp_pdf_file, output_file])


def shrink_pdf(
    input_file,
    output_file,
    tmpdir,
    dpi,
    *,
    max_pages=-1,
    use_existing_hocr=False,
):
    with tempfile.TemporaryDirectory(dir=tmpdir) as workdir:
        do_shrink(
            input_file,
            output_file,
            workdir=workdir,
            dpi=dpi,
            max_pages=max_pages,
            use_existing_hocr=use_existing_hocr,
        )


def main():
    args = parse_args()

    setup_logging(args.debug)

    check_dependencies()

    shrink_pdf(
        args.input_file,
        args.output_file,
        tmpdir=args.tmpdir,
        dpi=args.dpi,
        max_pages=args.max_pages,
        use_existing_hocr=args.use_existing_hocr,
    )


if __name__ == "__main__":
    main()
