Name:           perl-WebService-Solr
Version:        0.23
Release:        1%{?dist}
Summary:        Module to interface with the Solr (Lucene) webservice
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/WebService-Solr/
Source0:        http://www.cpan.org/modules/by-module/WebService/WebService-Solr-%{version}.tar.gz
Patch:          perl-WebService-Solr-utf8.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.0
BuildRequires:  perl(Any::Moose) >= 0.16
BuildRequires:  perl(Data::Page)
BuildRequires:  perl(Data::Pageset)
BuildRequires:  perl(Encode)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(JSON::XS)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Test::Mock::LWP) >= 0.05
BuildRequires:  perl(Test::More) >= 0.94
BuildRequires:  perl(URI) >= 1.28
BuildRequires:  perl(XML::Easy)
BuildRequires:  perl(XML::Simple)
Requires:       perl(Any::Moose) >= 0.16
Requires:       perl(Data::Page)
Requires:       perl(Data::Pageset)
Requires:       perl(Encode)
Requires:       perl(JSON::XS)
Requires:       perl(LWP::UserAgent)
Requires:       perl(URI) >= 1.28
Requires:       perl(XML::Easy)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
WebService::Solr is a client library for Apache Lucene's Solr; an enterprise-
grade indexing and searching platform.

%prep
%setup -q -n WebService-Solr-%{version}
# Patch WebService::Solr so that it does not doubly
# encode fields that are already utf8 encoded
# See: https://rt.cpan.org/Public/Bug/Display.html?id=47012
%patch -p1

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes foo README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Feb 07 2015 Rasan Rasch <rasan@nyu.edu> 0.23-1
- Specfile autogenerated by cpanspec 1.78.
